# -*- coding: utf-8 -*-
"""Accountproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5_szl8Ho_9qJKgIpZmUdupySw4EVVXo
"""

!python main.py